In [1]:
import os
import pandas as pd
import numpy as np
from time import time
from tqdm.notebook import tqdm
import pickle

from scipy.sparse import coo_matrix, csr_matrix

from lightfm.cross_validation import random_train_test_split
from lightfm import LightFM
from lightfm.data import Dataset
from lightfm.evaluation import precision_at_k, auc_score, recall_at_k

from hyperopt import fmin, hp, tpe, Trials

from sklearn.base import clone

## Normalization
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

C:\Users\SSAFY\anaconda3\envs\mini-project\lib\site-packages\lightfm\_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn(

In [2]:
# item_features = pd.read_csv("dataset/min_max_item_features.csv", index_col=0, encoding="UTF-8")
user_features = pd.read_csv("dataset/min_max_user_features.csv", index_col=0, encoding="UTF-8")
rating = pd.read_csv("dataset/rating.csv", index_col=0, encoding="UTF-8")
whisky = pd.read_csv("dataset/whisky.csv", index_col=0, encoding="UTF-8")

# Item Feature 재정의
---
- 다른 feature도 추가해보자

In [3]:
whisky

,whisky_id,link,image,name,avr_rating,category,location,total_rating,cost_rank,abv,...,herbal,oily,full_bodied,rich,sweet,salty,vanilla,tart,fruity,floral
0,0,/spirits/hibiki-21-year,https://ip-distiller.imgix.net/images/spirits/...,Hibiki 21 Year,9.01,Blended,Japan,861.0,5,43.00,...,30,20,80,80,85,15,20,25,85,50
1,1,/spirits/highland-park-18,https://ip-distiller.imgix.net/images/spirits/...,Highland Park 18 Year,8.89,Peated Single Malt,"Islands, Scotland",2988.0,4,43.00,...,20,40,70,80,70,40,50,50,70,20
2,2,/spirits/michter-s-20-year-kentucky-straight-b...,https://ip-distiller.imgix.net/images/spirits/...,Michter's 20 Year Kentucky Straight Bourbon (2...,9.00,Bourbon,"Kentucky, USA",10.0,5,57.10,...,0,15,80,90,85,5,30,25,35,0
3,3,/spirits/george-t-stagg-bourbon-fall-2019,https://ip-distiller.imgix.net/images/spirits/...,George T. Stagg Bourbon (Fall 2019),9.06,Bourbon,"Kentucky, USA",629.0,4,58.45,...,50,20,60,60,45,0,60,60,45,0
4,4,/spirits/bowmore-mizunara-cask-finish,https://ip-distiller.imgix.net/images/spirits/...,Bowmore Mizunara Cask Finish,7.86,Peated Single Malt,"Islay, Scotland",22.0,5,53.90,...,30,10,75,75,60,20,30,20,50,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3530,3530,/spirits/wild-turkey-spiced,https://ip-distiller.imgix.net/images/spirits/...,Wild Turkey Spiced,5.92,Flavored Whiskey,"Kentucky, USA",13.0,1,43.00,...,0,0,40,55,85,0,25,10,10,0
3531,3531,/spirits/seagram-s-seven-crown-american-blende...,https://ip-distiller.imgix.net/images/spirits/...,Seagram's 7 Crown American Blended Whiskey,4.31,Blended American Whiskey,USA,237.0,1,40.00,...,20,0,30,0,100,0,100,0,60,10
3532,3532,/spirits/11-wells-single-malt-whiskey,https://ip-distiller.imgix.net/images/spirits/...,11 Wells Single Malt Whiskey,6.00,American Single Malt,"Minnesota, USA",2.0,3,42.00,...,10,40,10,10,90,0,50,20,30,10
3533,3533,/spirits/immortal-spirits-early-whiskey,https://ip-distiller.imgix.net/images/spirits/...,Immortal Spirits Early Whiskey,2.00,Other Whiskey,"Oregon, USA",1.0,2,44.50,...,100,80,0,0,40,0,20,0,0,0
3534,3534,/spirits/triple-crown-blended-whiskey,https://ip-distiller.imgix.net/images/spirits/...,Triple Crown Blended Whiskey,4.88,Blended American Whiskey,"Missouri, USA",16.0,1,40.00,...,29,0,30,40,100,0,55,0,30,10

In [4]:
cols = whisky.columns.tolist()
cols = [cols[5]] + cols[8:10] + cols[11:] 
cols

['category',
 'cost_rank',
 'abv',
 'smoky',
 'peaty',
 'spicy',
 'herbal',
 'oily',
 'full_bodied',
 'rich',
 'sweet',
 'salty',
 'vanilla',
 'tart',
 'fruity',
 'floral']

## whisky

In [5]:
numeric_cols = cols[2:]
categorical_cols = cols[:2]

In [6]:
cate_df = whisky[categorical_cols]
numeric_df = whisky[numeric_cols]

### categorical variable
---
- category
- const_rank

In [7]:
le_category = LabelEncoder()
le_cost_rank = LabelEncoder()

cate_df[categorical_cols[0]] = le_category.fit_transform(cate_df[categorical_cols[0]])
cate_df[categorical_cols[1]] = le_cost_rank.fit_transform(cate_df[categorical_cols[1]])

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_24556\3312375797.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cate_df[categorical_cols[0]] = le_category.fit_transform(cate_df[categorical_cols[0]])
C:\Users\SSAFY\AppData\Local\Temp\ipykernel_24556\3312375797.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cate_df[categorical_cols[1]] = le_cost_rank.fit_transform(cate_df[categorical_cols[1]])

### numeric variable
---
- abv ~ floral

In [8]:
# Define the scalers
min_max_scaler = MinMaxScaler()

# Apply Min-Max normalization
numeric_df[numeric_cols] = min_max_scaler.fit_transform(whisky[numeric_cols])

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_24556\1236508202.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numeric_df[numeric_cols] = min_max_scaler.fit_transform(whisky[numeric_cols])

In [9]:
numeric_df

,abv,smoky,peaty,spicy,herbal,oily,full_bodied,rich,sweet,salty,vanilla,tart,fruity,floral
0,0.260,0.30,0.85,0.50,0.30,0.20,0.80,0.80,0.85,0.166667,0.20,0.25,0.85,0.526316
1,0.260,0.40,0.30,0.40,0.20,0.40,0.70,0.80,0.70,0.444444,0.50,0.50,0.70,0.210526
2,0.542,0.15,0.00,0.20,0.00,0.15,0.80,0.90,0.85,0.055556,0.30,0.25,0.35,0.000000
3,0.569,0.40,0.00,0.65,0.50,0.20,0.60,0.60,0.45,0.000000,0.60,0.60,0.45,0.000000
4,0.478,0.30,0.20,0.40,0.30,0.10,0.75,0.75,0.60,0.222222,0.30,0.20,0.50,0.052632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3530,0.260,0.35,0.00,0.20,0.00,0.00,0.40,0.55,0.85,0.000000,0.25,0.10,0.10,0.000000
3531,0.200,0.00,0.00,0.40,0.20,0.00,0.30,0.00,1.00,0.000000,1.00,0.00,0.60,0.105263
3532,0.240,0.90,0.10,0.10,0.10,0.40,0.10,0.10,0.90,0.000000,0.50,0.20,0.30,0.105263
3533,0.290,0.00,0.00,0.10,1.00,0.80,0.00,0.00,0.40,0.000000,0.20,0.00,0.00,0.000000
3534,0.200,0.31,0.00,0.40,0.29,0.00,0.30,0.40,1.00,0.000000,0.55,0.00,0.30,0.105263

In [10]:
numeric_df.describe()

,abv,smoky,peaty,spicy,herbal,oily,full_bodied,rich,sweet,salty,vanilla,tart,fruity,floral
count,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000,3535.000000
mean,0.350434,0.223089,0.087644,0.459165,0.262068,0.285881,0.546673,0.544320,0.543825,0.106170,0.429819,0.252537,0.442031,0.217884
std,0.128288,0.205434,0.194206,0.204274,0.194500,0.196807,0.186168,0.191708,0.183895,0.164596,0.210966,0.183111,0.226912,0.213100
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.260000,0.050000,0.000000,0.300000,0.100000,0.150000,0.400000,0.400000,0.400000,0.000000,0.250000,0.100000,0.250000,0.042105
50%,0.320000,0.200000,0.000000,0.450000,0.200000,0.250000,0.550000,0.550000,0.600000,0.000000,0.400000,0.200000,0.400000,0.157895
75%,0.400000,0.300000,0.000000,0.600000,0.400000,0.400000,0.700000,0.700000,0.700000,0.166667,0.600000,0.400000,0.600000,0.315789
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
item_features = pd.concat([cate_df, numeric_df], axis=1)

In [12]:
item_features

,category,cost_rank,abv,smoky,peaty,spicy,herbal,oily,full_bodied,rich,sweet,salty,vanilla,tart,fruity,floral
0,1,4,0.260,0.30,0.85,0.50,0.30,0.20,0.80,0.80,0.85,0.166667,0.20,0.25,0.85,0.526316
1,12,3,0.260,0.40,0.30,0.40,0.20,0.40,0.70,0.80,0.70,0.444444,0.50,0.50,0.70,0.210526
2,5,4,0.542,0.15,0.00,0.20,0.00,0.15,0.80,0.90,0.85,0.055556,0.30,0.25,0.35,0.000000
3,5,3,0.569,0.40,0.00,0.65,0.50,0.20,0.60,0.60,0.45,0.000000,0.60,0.60,0.45,0.000000
4,12,4,0.478,0.30,0.20,0.40,0.30,0.10,0.75,0.75,0.60,0.222222,0.30,0.20,0.50,0.052632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3530,8,0,0.260,0.35,0.00,0.20,0.00,0.00,0.40,0.55,0.85,0.000000,0.25,0.10,0.10,0.000000
3531,2,0,0.200,0.00,0.00,0.40,0.20,0.00,0.30,0.00,1.00,0.000000,1.00,0.00,0.60,0.105263
3532,0,2,0.240,0.90,0.10,0.10,0.10,0.40,0.10,0.10,0.90,0.000000,0.50,0.20,0.30,0.105263
3533,9,1,0.290,0.00,0.00,0.10,1.00,0.80,0.00,0.00,0.40,0.000000,0.20,0.00,0.00,0.000000
3534,2,0,0.200,0.31,0.00,0.40,0.29,0.00,0.30,0.40,1.00,0.000000,0.55,0.00,0.30,0.105263

## user_features 재정의

In [13]:
user_features

,cost_rank,smoky,peaty,spicy,herbal,oily,full_bodied,rich,sweet,salty,vanilla,tart,fruity,floral
0,4.0,0.20,0.30,0.4,0.20,0.1,0.6,0.5,0.70,0.222222,0.70,0.60,0.70,0.526316
1,5.0,0.30,0.30,0.6,0.40,0.7,0.8,0.7,0.70,0.444444,0.60,0.40,0.70,0.421053
2,5.0,0.30,0.85,0.5,0.30,0.2,0.8,0.8,0.85,0.166667,0.20,0.25,0.85,0.526316
3,5.0,0.20,0.00,0.6,0.40,0.3,0.7,0.7,0.60,0.111111,0.40,0.50,0.80,0.315789
4,4.0,0.00,0.00,0.2,0.40,0.6,0.6,0.8,0.70,0.000000,0.30,0.20,0.80,0.736842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119510,1.0,0.00,0.00,0.4,0.20,0.0,0.3,0.0,1.00,0.000000,1.00,0.00,0.60,0.105263
119511,1.0,0.00,0.00,0.4,0.20,0.0,0.3,0.0,1.00,0.000000,1.00,0.00,0.60,0.105263
119512,1.0,0.31,0.00,0.4,0.29,0.0,0.3,0.4,1.00,0.000000,0.55,0.00,0.30,0.105263
119513,1.0,0.31,0.00,0.4,0.29,0.0,0.3,0.4,1.00,0.000000,0.55,0.00,0.30,0.105263
119514,1.0,0.31,0.00,0.4,0.29,0.0,0.3,0.4,1.00,0.000000,0.55,0.00,0.30,0.105263

## user_features & item_features 정의

In [14]:
item_features = csr_matrix(item_features)
user_features = csr_matrix(user_features)

In [15]:
print(user_features)
user_features

  (0, 0)	4.0
  (0, 1)	0.2
  (0, 2)	0.3
  (0, 3)	0.4
  (0, 4)	0.2
  (0, 5)	0.1
  (0, 6)	0.6
  (0, 7)	0.5
  (0, 8)	0.7000000000000001
  (0, 9)	0.2222222222222222
  (0, 10)	0.7000000000000001
  (0, 11)	0.6
  (0, 12)	0.7000000000000001
  (0, 13)	0.5263157894736842
  (1, 0)	5.0
  (1, 1)	0.3
  (1, 2)	0.3
  (1, 3)	0.6
  (1, 4)	0.4
  (1, 5)	0.7000000000000001
  (1, 6)	0.8
  (1, 7)	0.7000000000000001
  (1, 8)	0.7000000000000001
  (1, 9)	0.4444444444444445
  (1, 10)	0.6
  :	:
  (119512, 7)	0.4
  (119512, 8)	1.0
  (119512, 10)	0.55
  (119512, 12)	0.3
  (119512, 13)	0.1052631578947368
  (119513, 0)	1.0
  (119513, 1)	0.31
  (119513, 3)	0.4
  (119513, 4)	0.29
  (119513, 6)	0.3
  (119513, 7)	0.4
  (119513, 8)	1.0
  (119513, 10)	0.55
  (119513, 12)	0.3
  (119513, 13)	0.1052631578947368
  (119514, 0)	1.0
  (119514, 1)	0.31
  (119514, 3)	0.4
  (119514, 4)	0.29
  (119514, 6)	0.3
  (119514, 7)	0.4
  (119514, 8)	1.0
  (119514, 10)	0.55
  (119514, 12)	0.3
  (119514, 13)	0.1052631578947368

<119515x14 sparse matrix of type '<class 'numpy.float64'>'
	with 1477379 stored elements in Compressed Sparse Row format>

In [16]:
unique_user = rating["user_id"].unique()

In [17]:
unique_user

array([     0,      1,      2, ..., 119512, 119513, 119514], dtype=int64)

### make Interactions

In [24]:
rating.shape

(908176, 3)

In [25]:
def create_user_item_interactions(rating, n_users, n_items):
    interactions = coo_matrix(
        (
            rating['rating'].values,
            (rating['user_id'].values, rating["whisky_id"].values)
        ),
        shape=(n_users, n_items)
    )
    return interactions

In [26]:
interactions = create_user_item_interactions(rating, rating["user_id"].nunique(), whisky["whisky_id"].nunique())

In [27]:
print(interactions)
interactions

  (0, 0)	9.0
  (1, 0)	7.0
  (2, 0)	9.0
  (3, 0)	10.0
  (4, 0)	9.0
  (5, 0)	7.0
  (6, 0)	10.0
  (7, 0)	7.0
  (8, 0)	10.0
  (9, 0)	10.0
  (10, 0)	9.0
  (11, 0)	9.0
  (12, 0)	8.0
  (13, 0)	8.0
  (14, 0)	10.0
  (15, 0)	10.0
  (16, 0)	9.0
  (17, 0)	9.0
  (18, 0)	8.0
  (19, 0)	9.0
  (20, 0)	9.0
  (21, 0)	10.0
  (22, 0)	9.0
  (23, 0)	9.0
  (24, 0)	9.0
  :	:
  (7636, 3531)	4.0
  (56292, 3531)	2.0
  (2670, 3531)	2.0
  (786, 3531)	2.0
  (5942, 3531)	6.0
  (15561, 3531)	2.0
  (25623, 3532)	6.0
  (2885, 3532)	6.0
  (7368, 3533)	2.0
  (69554, 3534)	10.0
  (4484, 3534)	2.0
  (85727, 3534)	5.0
  (43900, 3534)	4.0
  (16070, 3534)	8.0
  (29998, 3534)	8.0
  (7895, 3534)	4.0
  (104052, 3534)	5.0
  (31152, 3534)	2.0
  (119512, 3534)	6.0
  (2509, 3534)	4.0
  (4828, 3534)	4.0
  (119513, 3534)	2.0
  (119514, 3534)	8.0
  (3123, 3534)	4.0
  (95648, 3534)	2.0

<119515x3535 sparse matrix of type '<class 'numpy.float64'>'
	with 908176 stored elements in COOrdinate format>

## Train_Test data split

In [28]:
train_interactions, test_interactions = random_train_test_split(interactions, test_percentage=0.2, random_state=42)

In [29]:
train_interactions, valid_interactions = random_train_test_split(train_interactions, test_percentage=0.2, random_state=42)

## Model Define

In [19]:
class LightFMResizable(LightFM):
    """A LightFM that resizes the model to accomodate new users,
    items, and features"""

    def fit_partial(
        self,
        interactions,
        user_features=None,
        item_features=None,
        sample_weight=None,
        epochs=1,
        num_threads=1,
        verbose=False,
    ):
        try:
            self._check_initialized()
            self._resize(interactions, user_features, item_features)
        except ValueError:
            # This is the first call so just fit without resizing
            pass

        super().fit_partial(
            interactions,
            user_features,
            item_features,
            sample_weight,
            epochs,
            num_threads,
            verbose,
        )

        return self

    def _resize(self, interactions, user_features=None, item_features=None):
        """Resizes the model to accommodate new users/items/features"""

        no_components = self.no_components
        no_user_features, no_item_features = interactions.shape  # default

        if hasattr(user_features, "shape"):
            no_user_features = user_features.shape[-1]
        if hasattr(item_features, "shape"):
            no_item_features = item_features.shape[-1]

        if (
            no_user_features == self.user_embeddings.shape[0]
            and no_item_features == self.item_embeddings.shape[0]
        ):
            return self

        new_model = clone(self)
        new_model._initialize(no_components, no_item_features, no_user_features)

        # update all attributes from self._check_initialized
        for attr in (
            "item_embeddings",
            "item_embedding_gradients",
            "item_embedding_momentum",
            "item_biases",
            "item_bias_gradients",
            "item_bias_momentum",
            "user_embeddings",
            "user_embedding_gradients",
            "user_embedding_momentum",
            "user_biases",
            "user_bias_gradients",
            "user_bias_momentum",
        ):
            # extend attribute matrices with new rows/cols from
            # freshly initialized model with right shape
            old_array = getattr(self, attr)
            old_slice = [slice(None, i) for i in old_array.shape]
            new_array = getattr(new_model, attr)
            new_array[tuple(old_slice)] = old_array
            setattr(self, attr, new_array)

        return self

In [ ]:
import

In [ ]:
class WhizzleDataset(Dataset):
        """
        Add Normalization and 
        """

### Evaluation
---
- 1차 최적화 hyper parameter 결과
- Best Params : {'no_components': 40, 'learning_rate': 0.05, 'item_alpha': 0.01, 'user_alpha': 0.001}
- Best Values : 0.8078765869140625

In [47]:
model = LightFMResizable(
    no_components=40, learning_rate=0.05000, item_alpha=0.00500, user_alpha=0.00050,learning_schedule='adagrad',loss="warp", random_state=42
)
%time model.fit(interactions=train_interactions, user_features=user_features, item_features=item_features, epochs=10, verbose=True)

Epoch: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [05:34<00:00, 33.50s/it]

CPU times: total: 5min 34s
Wall time: 5min 35s

In [48]:
test_precision = precision_at_k(model, test_interactions, user_features=user_features, item_features=item_features, k=9).mean()
test_recall = recall_at_k(model, test_interactions,  user_features=user_features, item_features=item_features, k=9).mean()
test_auc = auc_score(model, test_interactions, user_features=user_features, item_features=item_features).mean()

print("Train precision: %.5f" % test_precision)
print("Test precision: %.5f" % test_recall)
print("Test AUC Score : %.5f" % test_auc)

Train precision: 0.00519
Test precision: 0.02467
Test AUC Score : 0.81449

### save

In [51]:
# save the model to a file
with open('min_max_lightfm.pkl', 'wb') as f:
    pickle.dump(model, f)

### Dataset

In [48]:
rating

        user_id  whisky_id  rating
0             0          0     9.0
1             1          0     7.0
2             2          0     9.0
3             3          0    10.0
4             4          0     9.0
...         ...        ...     ...
908171     4828       3534     4.0
908172   119513       3534     2.0
908173   119514       3534     8.0
908174     3123       3534     4.0
908175    95648       3534     2.0

[908176 rows x 3 columns]

In [56]:
from sklearn.model_selection import train_test_split

In [106]:
a_rating, b_rating = train_test_split(rating, test_size=0.2, random_state=42)

In [70]:
a_rating.shape

(726540, 3)

In [71]:
b_rating.shape

(181636, 3)

In [107]:
dataset = Dataset()

In [103]:
whisky.whisky_id.unique()

array([   0,    1,    2, ..., 3532, 3533, 3534], dtype=int64)

In [108]:
dataset.fit(
    users=rating["user_id"].unique(),
    items=whisky["whisky_id"].unique()
)

In [78]:
a_rating = a_rating.rename(columns={'whisky_id': 'item_id', "rating": "weight"})

In [ ]:
def make_iter_form(data):
    data = []
    for i, row in data.iterrows():

In [99]:
print(a_rating)

        user_id  item_id  weight
267858     3548      981     7.0
41052     24671      108     9.0
304281     5515     1085     6.0
542634    18673     1987    10.0
561123     1167     2053     8.0
...         ...      ...     ...
259178    10270      889     8.0
365838    14215     1296     6.0
131932     3664      584     7.0
671155     5194     2468     4.0
121958    45578      557     9.0

[726540 rows x 3 columns]

In [123]:
[(row['user_id'], row['whisky_id'], row['rating']) for index, row in a_rating.iterrows()]

[(3548.0, 981.0, 7.0),
 (24671.0, 108.0, 9.0),
 (5515.0, 1085.0, 6.0),
 (18673.0, 1987.0, 10.0),
 (1167.0, 2053.0, 8.0),
 (72820.0, 1031.0, 8.0),
 (62124.0, 3222.0, 6.0),
 (16412.0, 1053.0, 7.0),
 (77546.0, 1097.0, 4.0),
 (1318.0, 1976.0, 8.0),
 (41126.0, 1217.0, 10.0),
 (16546.0, 94.0, 10.0),
 (24390.0, 2254.0, 8.0),
 (17195.0, 1502.0, 8.0),
 (96941.0, 3349.0, 8.0),
 (15621.0, 609.0, 6.0),
 (8858.0, 2254.0, 7.0),
 (61799.0, 3223.0, 7.0),
 (20573.0, 752.0, 8.0),
 (106204.0, 2462.0, 8.0),
 (57468.0, 1983.0, 8.0),
 (1272.0, 2252.0, 7.0),
 (5658.0, 1968.0, 10.0),
 (10701.0, 801.0, 10.0),
 (13100.0, 1361.0, 7.0),
 (18258.0, 2241.0, 6.0),
 (8008.0, 1644.0, 7.0),
 (48321.0, 2386.0, 8.0),
 (10484.0, 1335.0, 8.0),
 (3408.0, 3214.0, 8.0),
 (4245.0, 2123.0, 8.0),
 (77569.0, 1097.0, 8.0),
 (109182.0, 2530.0, 5.0),
 (22704.0, 2358.0, 7.0),
 (83503.0, 3021.0, 6.0),
 (29777.0, 290.0, 9.0),
 (13065.0, 1987.0, 8.0),
 (29708.0, 1206.0, 9.0),
 (43500.0, 460.0, 9.0),
 (98258.0, 2486.0, 6.0),
 (91139.0, 2342.0, 7.0),
 (1048.0, 2986.0, 7.0),
 (9380.0, 405.0, 8.0),
 (412.0, 606.0, 6.0),
 (61815.0, 789.0, 8.0),
 (16558.0, 1775.0, 7.0),
 (4650.0, 1278.0, 10.0),
 (1043.0, 1321.0, 9.0),
 (2983.0, 2130.0, 6.0),
 (6491.0, 1974.0, 6.0),
 (10196.0, 3349.0, 6.0),
 (25558.0, 2860.0, 7.0),
 (102305.0, 2858.0, 10.0),
 (52818.0, 2673.0, 10.0),
 (3790.0, 2112.0, 5.0),
 (10525.0, 807.0, 8.0),
 (64407.0, 2379.0, 7.0),
 (18142.0, 605.0, 7.0),
 (28681.0, 1461.0, 9.0),
 (10380.0, 2652.0, 6.0),
 (5760.0, 1987.0, 8.0),
 (54358.0, 2854.0, 8.0),
 (14126.0, 3223.0, 6.0),
 (105481.0, 2918.0, 6.0),
 (29123.0, 752.0, 8.0),
 (6085.0, 1860.0, 8.0),
 (18185.0, 767.0, 9.0),
 (1318.0, 1674.0, 6.0),
 (2919.0, 2962.0, 7.0),
 (92185.0, 1669.0, 8.0),
 (26395.0, 2673.0, 7.0),
 (19644.0, 94.0, 10.0),
 (14525.0, 3349.0, 8.0),
 (82862.0, 1987.0, 8.0),
 (19919.0, 94.0, 8.0),
 (6323.0, 2860.0, 10.0),
 (77071.0, 1350.0, 10.0),
 (86575.0, 2665.0, 8.0),
 (71808.0, 1034.0, 7.0),
 (11264.0, 811.0, 8.0),
 (11308.0, 91.0, 10.0),
 (27470.0, 752.0, 2.0),
 (30725.0, 246.0, 9.0),
 (24077.0, 3006.0, 6.0),
 (1318.0, 609.0, 8.0),
 (80019.0, 1105.0, 10.0),
 (8642.0, 2475.0, 8.0),
 (71570.0, 1792.0, 8.0),
 (5702.0, 1218.0, 6.0),
 (24152.0, 97.0, 4.0),
 (18142.0, 1034.0, 7.0),
 (2545.0, 406.0, 6.0),
 (292.0, 1944.0, 6.0),
 (20006.0, 2473.0, 6.0),
 (66501.0, 1355.0, 8.0),
 (82276.0, 2360.0, 8.0),
 (9215.0, 3349.0, 8.0),
 (3096.0, 1974.0, 6.0),
 (2827.0, 1361.0, 8.0),
 (27185.0, 207.0, 10.0),
 (23430.0, 2652.0, 6.0),
 (12574.0, 2377.0, 8.0),
 (4366.0, 119.0, 8.0),
 (36122.0, 1322.0, 6.0),
 (36641.0, 1344.0, 7.0),
 (3775.0, 2547.0, 5.0),
 (69988.0, 817.0, 8.0),
 (22456.0, 1075.0, 9.0),
 (2029.0, 386.0, 8.0),
 (35028.0, 347.0, 7.0),
 (25835.0, 1359.0, 8.0),
 (28532.0, 182.0, 7.0),
 (18949.0, 1362.0, 7.0),
 (85137.0, 1359.0, 9.0),
 (5065.0, 409.0, 10.0),
 (19420.0, 2659.0, 6.0),
 (24610.0, 754.0, 8.0),
 (2250.0, 3509.0, 2.0),
 (105056.0, 2379.0, 8.0),
 (14567.0, 3384.0, 2.0),
 (18559.0, 3348.0, 8.0),
 (25586.0, 502.0, 10.0),
 (12248.0, 1317.0, 8.0),
 (16176.0, 1869.0, 7.0),
 (24611.0, 2915.0, 7.0),
 (17663.0, 608.0, 8.0),
 (30674.0, 596.0, 7.0),
 (11770.0, 2664.0, 6.0),
 (13485.0, 1860.0, 7.0),
 (72793.0, 2462.0, 8.0),
 (22215.0, 2234.0, 7.0),
 (10762.0, 2785.0, 8.0),
 (34589.0, 2379.0, 7.0),
 (9446.0, 1035.0, 8.0),
 (14450.0, 573.0, 8.0),
 (35914.0, 2675.0, 6.0),
 (17912.0, 246.0, 10.0),
 (22410.0, 1097.0, 5.0),
 (40742.0, 1367.0, 10.0),
 (75505.0, 2240.0, 8.0),
 (8512.0, 1075.0, 10.0),
 (7368.0, 242.0, 6.0),
 (8617.0, 1869.0, 8.0),
 (13667.0, 2673.0, 6.0),
 (14842.0, 1083.0, 8.0),
 (1288.0, 2665.0, 7.0),
 (71118.0, 2639.0, 6.0),
 (15206.0, 1647.0, 10.0),
 (34554.0, 1362.0, 8.0),
 (23928.0, 2486.0, 6.0),
 (14333.0, 814.0, 8.0),
 (63542.0, 804.0, 8.0),
 (111821.0, 2678.0, 8.0),
 (10375.0, 603.0, 8.0),
 (1554.0, 2321.0, 6.0),
 (26951.0, 1347.0, 10.0),
 (1335.0, 1216.0, 8.0),
 (6934.0, 614.0, 6.0),
 (7956.0, 1366.0, 10.0),
 (6022.0, 809.0, 8.0),
 (2764.0, 804.0, 4.0),
 (8535.0, 777.0, 0.0),
 (5926.0, 3008.0, 8.0),
 (10513.0, 2854.0, 8.0),
 (28837.0, 1661.0, 8.0),
 (5697.0, 2184.0, 7.0),
 (45150.0, 3349.0, 5.0),
 (30552.0, 1994.0, 8.0),
 (1206.0, 2236.0, 9.0),
 (51161.0, 817.0, 8.0),
 (4307.0, 85.0, 8.0),
 (78225.0, 1102.0, 10.0),
 (3101.0, 2486.0, 6.0),
 (47033.0, 1778.0, 8.0),
 (63763.0, 1561.0, 8.0),
 (51934.0, 1365.0, 6.0),
 (35457.0, 365.0, 7.0),
 (42308.0, 1609.0, 8.0),
 (109421.0, 3419.0, 6.0),
 (43699.0, 648.0, 7.0),
 (70615.0, 2241.0, 6.0),
 (57637.0, 2664.0, 6.0),
 (76188.0, 2476.0, 7.0),
 (14083.0, 2242.0, 4.0),
 (81065.0, 1986.0, 10.0),
 (4557.0, 1676.0, 10.0),
 (8914.0, 1584.0, 6.0),
 (3621.0, 2974.0, 6.0),
 (97797.0, 2678.0, 7.0),
 (115591.0, 3005.0, 8.0),
 (3964.0, 883.0, 10.0),
 (18065.0, 1368.0, 8.0),
 (107750.0, 2476.0, 9.0),
 (1208.0, 817.0, 8.0),
 (345.0, 1868.0, 10.0),
 (27623.0, 809.0, 7.0),
 (13440.0, 3245.0, 6.0),
 (1401.0, 312.0, 7.0),
 (153.0, 2857.0, 8.0),
 (25023.0, 3293.0, 8.0),
 (3825.0, 2104.0, 7.0),
 (42011.0, 409.0, 8.0),
 (118849.0, 3384.0, 6.0),
 (3962.0, 3306.0, 6.0),
 (3541.0, 2544.0, 7.0),
 (99316.0, 3025.0, 8.0),
 (5042.0, 470.0, 9.0),
 (20343.0, 609.0, 6.0),
 (17763.0, 1032.0, 4.0),
 (4209.0, 2241.0, 6.0),
 (11721.0, 2860.0, 8.0),
 (40412.0, 1367.0, 9.0),
 (17427.0, 1752.0, 8.0),
 (17335.0, 3377.0, 8.0),
 (22923.0, 2659.0, 4.0),
 (13759.0, 1081.0, 10.0),
 (25209.0, 1563.0, 8.0),
 (22548.0, 2981.0, 6.0),
 (51603.0, 1983.0, 8.0),
 (2427.0, 226.0, 10.0),
 (189.0, 2228.0, 4.0),
 (34041.0, 2250.0, 8.0),
 (40594.0, 1105.0, 8.0),
 (16950.0, 2379.0, 7.0),
 (12324.0, 1312.0, 7.0),
 (59510.0, 723.0, 10.0),
 (115176.0, 2932.0, 8.0),
 (9051.0, 3100.0, 4.0),
 (6482.0, 1461.0, 8.0),
 (9544.0, 650.0, 8.0),
 (41445.0, 2466.0, 6.0),
 (3699.0, 3129.0, 9.0),
 (28945.0, 1644.0, 8.0),
 (32753.0, 614.0, 8.0),
 (370.0, 1370.0, 10.0),
 (23904.0, 2254.0, 6.0),
 (23259.0, 1611.0, 6.0),
 (13542.0, 1104.0, 8.0),
 (46346.0, 557.0, 4.0),
 (16848.0, 3384.0, 5.0),
 (2616.0, 1548.0, 4.0),
 (20677.0, 3122.0, 8.0),
 (630.0, 597.0, 4.0),
 (2551.0, 2473.0, 6.0),
 (8113.0, 817.0, 8.0),
 (9807.0, 1668.0, 5.0),
 (48763.0, 1797.0, 7.0),
 (25677.0, 1103.0, 10.0),
 (19076.0, 3513.0, 9.0),
 (7578.0, 37.0, 10.0),
 (6641.0, 2771.0, 10.0),
 (35371.0, 2454.0, 6.0),
 (18534.0, 1344.0, 6.0),
 (79546.0, 1104.0, 10.0),
 (2249.0, 91.0, 8.0),
 (103412.0, 2254.0, 10.0),
 (2220.0, 1.0, 10.0),
 (30538.0, 3233.0, 3.0),
 (4163.0, 265.0, 8.0),
 (83980.0, 1344.0, 8.0),
 (56634.0, 1359.0, 8.0),
 (34696.0, 2848.0, 6.0),
 (14777.0, 557.0, 4.0),
 (23454.0, 97.0, 8.0),
 (96999.0, 2091.0, 8.0),
 (12275.0, 2431.0, 7.0),
 (59280.0, 1361.0, 7.0),
 (77040.0, 2242.0, 6.0),
 (100200.0, 2605.0, 6.0),
 (12148.0, 3223.0, 8.0),
 (82488.0, 2678.0, 4.0),
 (23491.0, 2604.0, 4.0),
 (19195.0, 1368.0, 7.0),
 (12246.0, 3292.0, 7.0),
 (34115.0, 1692.0, 7.0),
 (11297.0, 91.0, 8.0),
 (119285.0, 3483.0, 6.0),
 (13891.0, 799.0, 8.0),
 (7380.0, 1368.0, 6.0),
 (3911.0, 807.0, 9.0),
 (42808.0, 809.0, 8.0),
 (29689.0, 1361.0, 6.0),
 (23206.0, 1105.0, 8.0),
 (14512.0, 2978.0, 6.0),
 (24296.0, 408.0, 8.0),
 (77177.0, 2108.0, 7.0),
 (103168.0, 3349.0, 10.0),
 (14618.0, 2670.0, 8.0),
 (1639.0, 3332.0, 7.0),
 (34762.0, 2604.0, 8.0),
 (2284.0, 1781.0, 5.0),
 (257.0, 609.0, 9.0),
 (23128.0, 3006.0, 8.0),
 (7629.0, 1981.0, 6.0),
 (40386.0, 604.0, 10.0),
 (26262.0, 2251.0, 8.0),
 (59602.0, 2664.0, 8.0),
 (20472.0, 1680.0, 8.0),
 (53583.0, 608.0, 9.0),
 (30451.0, 244.0, 8.0),
 (75868.0, 3384.0, 4.0),
 (78503.0, 2675.0, 6.0),
 (40344.0, 1273.0, 8.0),
 (79785.0, 1105.0, 7.0),
 (2993.0, 1.0, 10.0),
 (15332.0, 3292.0, 4.0),
 (1953.0, 3175.0, 4.0),
 (66456.0, 2468.0, 6.0),
 (32692.0, 545.0, 8.0),
 (18120.0, 1097.0, 8.0),
 (27477.0, 1347.0, 8.0),
 (3891.0, 2662.0, 6.0),
 (28478.0, 3301.0, 8.0),
 (16286.0, 814.0, 6.0),
 (18316.0, 1317.0, 6.0),
 (98009.0, 2251.0, 8.0),
 (42873.0, 2298.0, 9.0),
 (15559.0, 92.0, 8.0),
 (11490.0, 1359.0, 8.0),
 (88922.0, 1960.0, 4.0),
 (79922.0, 2254.0, 4.0),
 (7561.0, 1073.0, 10.0),
 (8185.0, 1634.0, 6.0),
 (3480.0, 1678.0, 8.0),
 (82562.0, 1952.0, 8.0),
 (15476.0, 804.0, 6.0),
 (30620.0, 1833.0, 8.0),
 (106798.0, 2468.0, 6.0),
 (25334.0, 3384.0, 6.0),
 (28926.0, 2745.0, 7.0),
 (90595.0, 2527.0, 8.0),
 (88.0, 1882.0, 8.0),
 (72241.0, 1008.0, 7.0),
 (47084.0, 1619.0, 7.0),
 (105487.0, 2464.0, 8.0),
 (16960.0, 609.0, 10.0),
 (107050.0, 2468.0, 4.0),
 (14929.0, 92.0, 6.0),
 (1046.0, 1206.0, 8.0),
 (47463.0, 584.0, 8.0),
 (31475.0, 2604.0, 6.0),
 (59244.0, 1860.0, 4.0),
 (25248.0, 2350.0, 8.0),
 (10829.0, 810.0, 4.0),
 (27361.0, 1823.0, 6.0),
 (15028.0, 2473.0, 6.0),
 (91777.0, 2849.0, 8.0),
 (21169.0, 3031.0, 8.0),
 (4972.0, 151.0, 10.0),
 (147.0, 2829.0, 6.0),
 (33732.0, 330.0, 10.0),
 (8771.0, 885.0, 9.0),
 (2660.0, 602.0, 8.0),
 (10041.0, 1106.0, 6.0),
 (44213.0, 1359.0, 10.0),
 (6129.0, 598.0, 8.0),
 (50739.0, 862.0, 7.0),
 (23833.0, 602.0, 10.0),
 (6313.0, 377.0, 6.0),
 (63958.0, 2486.0, 10.0),
 (109158.0, 2530.0, 6.0),
 (9174.0, 2453.0, 10.0),
 (20559.0, 1364.0, 8.0),
 (60924.0, 1102.0, 10.0),
 (21757.0, 1368.0, 6.0),
 (6461.0, 785.0, 9.0),
 (32192.0, 2468.0, 6.0),
 (70717.0, 2530.0, 5.0),
 (75507.0, 1548.0, 8.0),
 (89989.0, 1601.0, 6.0),
 (3606.0, 1661.0, 9.0),
 (3555.0, 457.0, 10.0),
 (65720.0, 3292.0, 7.0),
 (9690.0, 1599.0, 6.0),
 (1048.0, 1104.0, 8.0),
 (83653.0, 1341.0, 10.0),
 (20097.0, 1104.0, 6.0),
 (24663.0, 1273.0, 7.0),
 (7702.0, 1348.0, 8.0),
 (24736.0, 1776.0, 8.0),
 (11564.0, 1976.0, 9.0),
 (18534.0, 598.0, 8.0),
 (9894.0, 1939.0, 8.0),
 (118513.0, 3349.0, 7.0),
 (17362.0, 1332.0, 8.0),
 (67643.0, 2472.0, 8.0),
 (72044.0, 2473.0, 6.0),
 (1144.0, 2163.0, 10.0),
 (62138.0, 789.0, 6.0),
 (107334.0, 2486.0, 7.0),
 (22319.0, 97.0, 8.0),
 (1211.0, 616.0, 7.0),
 (11197.0, 1075.0, 10.0),
 (5198.0, 2456.0, 3.0),
 (6935.0, 1329.0, 6.0),
 (22492.0, 614.0, 8.0),
 (70591.0, 2034.0, 9.0),
 (92449.0, 1674.0, 6.0),
 (28192.0, 1721.0, 6.0),
 (8553.0, 1669.0, 7.0),
 (1195.0, 2860.0, 7.0),
 (206.0, 3350.0, 2.0),
 (100166.0, 2953.0, 8.0),
 (104127.0, 2333.0, 8.0),
 (36562.0, 817.0, 8.0),
 (86075.0, 2675.0, 7.0),
 (1224.0, 2771.0, 7.0),
 (9088.0, 2126.0, 8.0),
 (2156.0, 2672.0, 8.0),
 (14199.0, 1666.0, 8.0),
 (10668.0, 1907.0, 6.0),
 (15273.0, 2252.0, 6.0),
 (24135.0, 2245.0, 10.0),
 (10158.0, 85.0, 10.0),
 (13818.0, 156.0, 10.0),
 (25664.0, 2661.0, 6.0),
 (103155.0, 2254.0, 8.0),
 (12762.0, 1368.0, 10.0),
 (25761.0, 1206.0, 8.0),
 (22070.0, 828.0, 7.0),
 (35795.0, 809.0, 10.0),
 (3340.0, 1680.0, 6.0),
 (40542.0, 3486.0, 6.0),
 (3879.0, 2544.0, 7.0),
 (28803.0, 2050.0, 8.0),
 (14082.0, 120.0, 8.0),
 (83970.0, 1344.0, 10.0),
 (40964.0, 408.0, 8.0),
 (10179.0, 817.0, 8.0),
 (113074.0, 2823.0, 6.0),
 (92295.0, 1672.0, 10.0),
 (70592.0, 862.0, 8.0),
 (86945.0, 1368.0, 10.0),
 (28180.0, 1869.0, 8.0),
 (90835.0, 1644.0, 8.0),
 (70807.0, 895.0, 7.0),
 (17966.0, 1655.0, 6.0),
 (23083.0, 1669.0, 8.0),
 (34369.0, 2254.0, 6.0),
 (2351.0, 958.0, 8.0),
 (8682.0, 1075.0, 8.0),
 (21717.0, 1028.0, 10.0),
 (17397.0, 1470.0, 8.0),
 (28677.0, 2466.0, 5.0),
 (4901.0, 1105.0, 7.0),
 (2807.0, 224.0, 10.0),
 (3795.0, 394.0, 8.0),
 (16541.0, 2673.0, 6.0),
 (12683.0, 578.0, 8.0),
 (6591.0, 394.0, 8.0),
 (30879.0, 2488.0, 5.0),
 (4885.0, 410.0, 6.0),
 (112936.0, 2797.0, 6.0),
 (8846.0, 3349.0, 4.0),
 (2617.0, 39.0, 8.0),
 (11788.0, 1655.0, 5.0),
 (530.0, 79.0, 8.0),
 (35362.0, 3503.0, 4.0),
 (103921.0, 2311.0, 8.0),
 (23547.0, 2932.0, 8.0),
 (83041.0, 2475.0, 8.0),
 (3637.0, 609.0, 9.0),
 (18651.0, 1922.0, 8.0),
 (67406.0, 1655.0, 10.0),
 (11841.0, 2242.0, 6.0),
 (20041.0, 94.0, 10.0),
 (24650.0, 3129.0, 7.0),
 (25552.0, 900.0, 8.0),
 (9183.0, 2612.0, 8.0),
 (6006.0, 2847.0, 6.0),
 (28793.0, 817.0, 8.0),
 (66227.0, 2850.0, 8.0),
 (1071.0, 1676.0, 9.0),
 (6820.0, 2273.0, 8.0),
 (20255.0, 94.0, 8.0),
 (89806.0, 2679.0, 6.0),
 (18277.0, 2469.0, 7.0),
 (14529.0, 1983.0, 8.0),
 (22272.0, 584.0, 8.0),
 (10255.0, 2379.0, 8.0),
 (2842.0, 1605.0, 8.0),
 (8712.0, 1034.0, 8.0),
 (7319.0, 1104.0, 8.0),
 (85529.0, 2679.0, 6.0),
 (5638.0, 394.0, 4.0),
 (996.0, 1.0, 9.0),
 (666.0, 1282.0, 6.0),
 (26669.0, 3223.0, 8.0),
 (42985.0, 2676.0, 9.0),
 (51012.0, 787.0, 8.0),
 (42865.0, 2468.0, 6.0),
 (55346.0, 609.0, 10.0),
 (11805.0, 2679.0, 5.0),
 (4756.0, 1680.0, 4.0),
 (24978.0, 112.0, 9.0),
 (17703.0, 1317.0, 8.0),
 (23457.0, 3531.0, 2.0),
 (1430.0, 723.0, 8.0),
 (6963.0, 2785.0, 6.0),
 (14023.0, 3008.0, 7.0),
 (55262.0, 2453.0, 10.0),
 (34570.0, 1359.0, 8.0),
 (23947.0, 240.0, 6.0),
 (14068.0, 92.0, 10.0),
 (17700.0, 1104.0, 8.0),
 (47101.0, 578.0, 8.0),
 (12023.0, 94.0, 8.0),
 (81475.0, 2234.0, 8.0),
 (32973.0, 1368.0, 9.0),
 (40160.0, 1987.0, 8.0),
 (37896.0, 1287.0, 8.0),
 (25945.0, 3006.0, 6.0),
 (22463.0, 787.0, 6.0),
 (8766.0, 687.0, 7.0),
 (1061.0, 3129.0, 7.0),
 (10252.0, 3293.0, 7.0),
 (8446.0, 1359.0, 10.0),
 (24619.0, 1386.0, 8.0),
 (24385.0, 2241.0, 6.0),
 (67249.0, 1470.0, 9.0),
 (92378.0, 2476.0, 6.0),
 (24722.0, 584.0, 9.0),
 (55062.0, 609.0, 10.0),
 (113822.0, 2854.0, 8.0),
 (32799.0, 2234.0, 7.0),
 (24302.0, 810.0, 8.0),
 (46369.0, 1660.0, 8.0),
 (34227.0, 645.0, 10.0),
 (43527.0, 817.0, 10.0),
 (31346.0, 249.0, 10.0),
 (39773.0, 2672.0, 8.0),
 (1415.0, 1102.0, 8.0),
 (28926.0, 1641.0, 7.0),
 (32505.0, 807.0, 7.0),
 (18858.0, 1095.0, 8.0),
 (8109.0, 3068.0, 7.0),
 (36813.0, 1273.0, 6.0),
 (10955.0, 2753.0, 6.0),
 (17357.0, 510.0, 2.0),
 (36011.0, 1359.0, 8.0),
 (42477.0, 1075.0, 8.0),
 (35169.0, 1091.0, 10.0),
 (61008.0, 2500.0, 7.0),
 (8232.0, 1820.0, 2.0),
 (12506.0, 1788.0, 7.0),
 (71650.0, 977.0, 4.0),
 (15179.0, 614.0, 8.0),
 (2655.0, 92.0, 6.0),
 (3790.0, 2445.0, 7.0),
 (8323.0, 757.0, 10.0),
 (9006.0, 2164.0, 4.0),
 (33620.0, 322.0, 8.0),
 (62346.0, 1347.0, 9.0),
 (43428.0, 1104.0, 9.0),
 (118101.0, 3306.0, 7.0),
 (242.0, 2025.0, 6.0),
 (85743.0, 1566.0, 8.0),
 (23507.0, 1344.0, 10.0),
 (5697.0, 817.0, 8.0),
 (11095.0, 1991.0, 8.0),
 (31754.0, 257.0, 8.0),
 (6775.0, 1922.0, 7.0),
 (30883.0, 3009.0, 2.0),
 (14047.0, 1990.0, 8.0),
 (27918.0, 2790.0, 4.0),
 (6952.0, 1056.0, 8.0),
 (75191.0, 1097.0, 10.0),
 (25117.0, 3469.0, 4.0),
 (88796.0, 1519.0, 7.0),
 (21677.0, 1344.0, 6.0),
 (26248.0, 1017.0, 9.0),
 (15092.0, 559.0, 8.0),
 (8621.0, 1273.0, 7.0),
 (21973.0, 1097.0, 8.0),
 (17207.0, 405.0, 9.0),
 (115561.0, 3001.0, 9.0),
 (5564.0, 2220.0, 6.0),
 (6576.0, 1560.0, 8.0),
 (61684.0, 2665.0, 8.0),
 (8466.0, 1663.0, 10.0),
 (7981.0, 39.0, 10.0),
 (11938.0, 609.0, 8.0),
 (13807.0, 1987.0, 9.0),
 (29926.0, 1085.0, 9.0),
 (69463.0, 1368.0, 8.0),
 (47258.0, 3292.0, 4.0),
 (93939.0, 2476.0, 6.0),
 (6911.0, 1347.0, 6.0),
 (19044.0, 2254.0, 6.0),
 (75079.0, 1359.0, 10.0),
 (24904.0, 1105.0, 8.0),
 (55802.0, 609.0, 10.0),
 (80913.0, 1153.0, 6.0),
 (4142.0, 3006.0, 8.0),
 (1957.0, 600.0, 8.0),
 (69318.0, 3223.0, 8.0),
 (32857.0, 466.0, 8.0),
 (10147.0, 2673.0, 8.0),
 (113946.0, 2857.0, 6.0),
 (31408.0, 251.0, 10.0),
 (103117.0, 2586.0, 6.0),
 (41808.0, 1104.0, 9.0),
 (7859.0, 1081.0, 7.0),
 (18054.0, 1956.0, 7.0),
 (15949.0, 1359.0, 6.0),
 (24981.0, 3006.0, 7.0),
 (19591.0, 1655.0, 8.0),
 (12334.0, 2104.0, 7.0),
 (34063.0, 1105.0, 7.0),
 (19278.0, 939.0, 10.0),
 (21552.0, 3218.0, 6.0),
 (2941.0, 804.0, 8.0),
 (65947.0, 2254.0, 8.0),
 (10651.0, 1669.0, 8.0),
 (8119.0, 2291.0, 6.0),
 (64813.0, 807.0, 8.0),
 (30364.0, 242.0, 8.0),
 (8102.0, 605.0, 6.0),
 (40347.0, 789.0, 8.0),
 (20304.0, 1975.0, 6.0),
 (25930.0, 817.0, 8.0),
 (60303.0, 2476.0, 8.0),
 (86215.0, 1366.0, 8.0),
 (7047.0, 596.0, 8.0),
 (98024.0, 2679.0, 6.0),
 (33209.0, 377.0, 9.0),
 (31220.0, 2673.0, 7.0),
 (969.0, 2324.0, 8.0),
 (19519.0, 970.0, 8.0),
 (17828.0, 1674.0, 6.0),
 (2337.0, 920.0, 8.0),
 (13027.0, 1970.0, 10.0),
 (1620.0, 591.0, 9.0),
 (78560.0, 1976.0, 6.0),
 (2383.0, 1324.0, 8.0),
 (4467.0, 811.0, 8.0),
 (3835.0, 1599.0, 7.0),
 (461.0, 2670.0, 8.0),
 (7886.0, 278.0, 9.0),
 (17922.0, 1075.0, 8.0),
 (80570.0, 2232.0, 8.0),
 (6037.0, 3021.0, 6.0),
 (15745.0, 92.0, 8.0),
 (10340.0, 603.0, 8.0),
 (110246.0, 2655.0, 7.0),
 (12464.0, 1470.0, 9.0),
 (9926.0, 398.0, 10.0),
 (38632.0, 614.0, 10.0),
 (20631.0, 94.0, 8.0),
 (85473.0, 1976.0, 8.0),
 (66999.0, 1325.0, 6.0),
 (66693.0, 3292.0, 6.0),
 (10795.0, 1926.0, 8.0),
 (66724.0, 2523.0, 8.0),
 (56527.0, 1105.0, 8.0),
 (44744.0, 1994.0, 5.0),
 (24308.0, 97.0, 8.0),
 (25458.0, 1012.0, 9.0),
 (3620.0, 2860.0, 8.0),
 (117451.0, 3265.0, 6.0),
 (8529.0, 43.0, 9.0),
 (108054.0, 2483.0, 4.0),
 (891.0, 3045.0, 5.0),
 (23545.0, 817.0, 7.0),
 (23749.0, 3006.0, 6.0),
 (41198.0, 1106.0, 7.0),
 (103355.0, 2254.0, 8.0),
 (97023.0, 1987.0, 9.0),
 (29142.0, 394.0, 8.0),
 (88310.0, 2243.0, 8.0),
 (32992.0, 817.0, 8.0),
 (11920.0, 1097.0, 9.0),
 (37614.0, 1322.0, 8.0),
 (21433.0, 1482.0, 8.0),
 (13066.0, 1075.0, 9.0),
 (55128.0, 2425.0, 8.0),
 (26227.0, 1034.0, 8.0),
 (30829.0, 2486.0, 7.0),
 (113125.0, 2829.0, 6.0),
 (42110.0, 1104.0, 10.0),
 (20594.0, 1317.0, 7.0),
 (112566.0, 3195.0, 6.0),
 (83750.0, 3029.0, 6.0),
 (1934.0, 3122.0, 8.0),
 (71357.0, 935.0, 8.0),
 (88431.0, 2797.0, 8.0),
 (98030.0, 2673.0, 8.0),
 (3979.0, 1364.0, 7.0),
 (49301.0, 2993.0, 8.0),
 (35479.0, 1081.0, 8.0),
 (113518.0, 2879.0, 6.0),
 (5925.0, 580.0, 10.0),
 (18134.0, 2483.0, 6.0),
 (27910.0, 2403.0, 6.0),
 (995.0, 94.0, 8.0),
 (93114.0, 2290.0, 8.0),
 (59660.0, 1621.0, 9.0),
 (7753.0, 2468.0, 2.0),
 (10260.0, 3209.0, 7.0),
 (5983.0, 588.0, 2.0),
 (37620.0, 789.0, 8.0),
 (9978.0, 2253.0, 10.0),
 (11666.0, 3006.0, 8.0),
 (33782.0, 3377.0, 7.0),
 (3879.0, 757.0, 8.0),
 (88324.0, 1470.0, 8.0),
 (97804.0, 1994.0, 4.0),
 (53960.0, 2473.0, 7.0),
 (43074.0, 432.0, 8.0),
 (14261.0, 801.0, 8.0),
 (96788.0, 1984.0, 10.0),
 (102034.0, 3021.0, 6.0),
 (98306.0, 1994.0, 8.0),
 (30700.0, 246.0, 9.0),
 (4808.0, 1974.0, 6.0),
 (77105.0, 1096.0, 9.0),
 (23769.0, 395.0, 8.0),
 (19003.0, 3031.0, 6.0),
 (47847.0, 991.0, 8.0),
 (114321.0, 2860.0, 8.0),
 (13543.0, 1078.0, 10.0),
 (888.0, 194.0, 7.0),
 (5066.0, 97.0, 10.0),
 (10874.0, 2830.0, 8.0),
 (41777.0, 811.0, 9.0),
 (26410.0, 3384.0, 4.0),
 (47396.0, 584.0, 5.0),
 (1469.0, 1104.0, 6.0),
 (88122.0, 1797.0, 9.0),
 (25377.0, 3501.0, 6.0),
 (387.0, 2445.0, 8.0),
 (36452.0, 3209.0, 7.0),
 (16616.0, 341.0, 8.0),
 (26063.0, 674.0, 8.0),
 (10968.0, 557.0, 6.0),
 (47940.0, 2333.0, 10.0),
 (1123.0, 397.0, 8.0),
 (1526.0, 1355.0, 7.0),
 (112043.0, 3349.0, 6.0),
 (438.0, 2469.0, 7.0),
 (37426.0, 2304.0, 7.0),
 (3727.0, 584.0, 8.0),
 (32867.0, 2816.0, 5.0),
 (12161.0, 2486.0, 6.0),
 (8584.0, 816.0, 8.0),
 (23745.0, 310.0, 7.0),
 (63873.0, 804.0, 8.0),
 (7391.0, 715.0, 8.0),
 (63648.0, 2476.0, 6.0),
 (238.0, 395.0, 7.0),
 (6934.0, 1308.0, 4.0),
 (20818.0, 1663.0, 10.0),
 (10339.0, 2444.0, 6.0),
 (110501.0, 2661.0, 7.0),
 (1611.0, 591.0, 10.0),
 (1490.0, 2254.0, 8.0),
 (3977.0, 2977.0, 6.0),
 (104600.0, 2365.0, 8.0),
 (25359.0, 1098.0, 8.0),
 (15954.0, 1976.0, 8.0),
 (29477.0, 1675.0, 8.0),
 (8168.0, 2896.0, 6.0),
 (38509.0, 746.0, 10.0),
 (21488.0, 767.0, 9.0),
 (4487.0, 2663.0, 8.0),
 (15651.0, 1086.0, 2.0),
 (19253.0, 3386.0, 7.0),
 (329.0, 1619.0, 8.0),
 (76078.0, 2242.0, 8.0),
 (883.0, 40.0, 8.0),
 (45166.0, 545.0, 10.0),
 (3092.0, 1103.0, 6.0),
 (17481.0, 1676.0, 8.0),
 (34352.0, 2888.0, 7.0),
 (3333.0, 409.0, 10.0),
 (1318.0, 3349.0, 6.0),
 (22285.0, 2304.0, 8.0),
 (35622.0, 367.0, 10.0),
 (48050.0, 1341.0, 8.0),
 (35120.0, 410.0, 10.0),
 (10646.0, 1663.0, 8.0),
 (17052.0, 3408.0, 8.0),
 (5666.0, 589.0, 10.0),
 (917.0, 1674.0, 8.0),
 (8858.0, 2241.0, 7.0),
 (36796.0, 2254.0, 8.0),
 (14000.0, 1317.0, 8.0),
 (7865.0, 2104.0, 7.0),
 (2824.0, 614.0, 8.0),
 (12655.0, 1931.0, 6.0),
 (47954.0, 1655.0, 10.0),
 (16919.0, 812.0, 7.0),
 (16961.0, 1061.0, 8.0),
 (6670.0, 2125.0, 10.0),
 (5894.0, 2673.0, 10.0),
 (32702.0, 289.0, 8.0),
 (40943.0, 2716.0, 8.0),
 (72442.0, 2328.0, 9.0),
 (95148.0, 2211.0, 10.0),
 (51201.0, 3169.0, 7.0),
 (13312.0, 1348.0, 8.0),
 (32526.0, 2974.0, 5.0),
 (4003.0, 2343.0, 5.0),
 (1944.0, 3409.0, 6.0),
 (2904.0, 1106.0, 10.0),
 (66373.0, 2468.0, 6.0),
 (678.0, 12.0, 10.0),
 (5575.0, 784.0, 10.0),
 (5058.0, 497.0, 8.0),
 (8973.0, 2254.0, 6.0),
 (20086.0, 609.0, 10.0),
 (14210.0, 804.0, 4.0),
 (5853.0, 2197.0, 6.0),
 (53755.0, 609.0, 8.0),

In [109]:
%time a_interactions, a_weights = dataset.build_interactions((row['user_id'], row['whisky_id'], row['rating']) for index, row in a_rating.iterrows())

CPU times: total: 29.9 s
Wall time: 30.4 s

In [111]:
b_rating.loc[b_rating["user_id"]==0]

        user_id  whisky_id  rating
0             0          0     9.0
231208        0        811     9.0
120472        0        546     8.0

In [121]:
a_rating.loc[a_rating["user_id"]==119513]

        user_id  whisky_id  rating
908172   119513       3534     2.0

In [110]:
print(a_rating.sort_values(by="user_id"))

        user_id  whisky_id  rating
419372        0       1370     8.0
548651        0       1994     6.0
656523        0       2451     3.0
491750        0       1769     8.0
300209        1       1081     9.0
...         ...        ...     ...
908039   119509       3531     3.0
908057   119510       3531    10.0
908128   119511       3531     8.0
908169   119512       3534     6.0
908172   119513       3534     2.0

[726540 rows x 3 columns]

In [113]:
a_rating

        user_id  whisky_id  rating
267858     3548        981     7.0
41052     24671        108     9.0
304281     5515       1085     6.0
542634    18673       1987    10.0
561123     1167       2053     8.0
...         ...        ...     ...
259178    10270        889     8.0
365838    14215       1296     6.0
131932     3664        584     7.0
671155     5194       2468     4.0
121958    45578        557     9.0

[726540 rows x 3 columns]

In [119]:
a_weights.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [7., 0., 0., ..., 0., 0., 0.],
       [9., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 6.],
       [0., 0., 0., ..., 0., 0., 2.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### b_rating 추가

In [ ]:
dataset.fit_partial(users=)

### load

In [20]:
 mm_lfm = pickle.load(open('min_max_lightfm.pkl', 'rb'))

In [85]:
whisky.columns.tolist()

['whisky_id',
 'link',
 'image',
 'name',
 'avr_rating',
 'category',
 'location',
 'total_rating',
 'cost_rank',
 'abv',
 'cask_type',
 'smoky',
 'peaty',
 'spicy',
 'herbal',
 'oily',
 'full_bodied',
 'rich',
 'sweet',
 'salty',
 'vanilla',
 'tart',
 'fruity',
 'floral']

In [88]:
cols = ["name","category", "cost_rank", "abv", 'smoky','peaty','spicy','herbal','oily','full_bodied','rich','sweet','salty','vanilla','tart','fruity', 'floral']

In [90]:
wi = rating.loc[rating["user_id"] == 4828].sort_values(by="rating", ascending=False).whisky_id
whisky.loc[wi, cols]

,name,category,cost_rank,abv,smoky,peaty,spicy,herbal,oily,full_bodied,rich,sweet,salty,vanilla,tart,fruity,floral
10,"Booker's Bourbon Batch 2015-01 ""Big Man, Small...",Bourbon,3,64.35,15,0,35,5,20,80,80,75,10,30,20,40,0
1089,Glenlivet 18 Year,Single Malt,3,43.00,20,0,50,0,20,70,70,80,0,60,50,80,30
2227,The Irishman Single Malt,Single Malt,2,40.00,20,0,60,30,20,50,50,60,0,40,50,80,30
1105,Maker's Mark 46 French Oaked,Bourbon,2,47.00,30,0,80,20,10,60,60,70,10,80,50,30,20
1994,Maker's Mark Bourbon,Bourbon,2,45.00,10,0,40,30,10,50,70,80,0,90,20,10,0
609,Lagavulin 16 Year,Peated Single Malt,3,43.00,60,80,60,50,70,80,70,40,60,40,20,40,10
3008,Smooth Ambler Old Scout Bourbon 7 Year,Bourbon,2,49.50,0,0,25,15,0,60,60,70,0,15,10,15,0
410,Elijah Craig 12 Year,Bourbon,2,47.00,40,0,50,30,40,60,50,70,50,40,20,40,20
3381,Concannon Irish Whiskey,Blended,1,40.00,54,0,32,85,62,68,42,78,43,75,28,73,60
1656,Tomatin 18 Year Oloroso Sherry Casks,Single Malt,3,46.00,50,20,60,60,20,50,50,60,20,30,30,60,60
1679,Redbreast 15 Year,Single Pot Still,4,46.00,30,10,70,20,30,50,50,70,10,60,50,70,30
94,Laphroaig 10 Year,Peated Single Malt,3,43.00,70,90,50,20,60,60,40,60,30,70,40,60,30
407,Baker's Small Batch Bourbon,Bourbon,2,53.50,20,0,60,10,40,70,70,40,0,30,20,20,20
2247,Glenlivet 15 Year French Oak Reserve,Single Malt,3,40.00,20,10,70,20,30,50,50,20,10,70,40,60,30
1034,Maker's Mark Cask Strength,Bourbon,3,56.60,20,0,90,40,50,70,80,60,50,90,0,60,0
3100,Ardmore Legacy,Peated Single Malt,2,40.00,10,10,20,50,20,30,30,20,0,30,10,10,60
2604,Jameson Caskmates Stout Edition,Blended,2,40.00,40,0,50,30,30,80,90,80,0,60,20,10,0
2843,Tomatin 12 Year Bourbon & Sherry Casks,Single Malt,2,43.00,30,10,60,50,40,40,40,50,20,30,50,40,50
3027,Dancing Pines Bourbon,Bourbon,2,44.00,5,0,0,10,0,10,10,50,0,45,0,50,40
815,Bowmore 12 Year,Peated Single Malt,2,40.00,40,50,30,10,30,60,70,80,60,70,30,70,30
2435,Rough Rider Straight Bourbon,Bourbon,2,45.00,0,0,15,0,10,80,80,85,0,20,0,40,5
2852,Peach Street Colorado Straight Bourbon,Bourbon,3,46.00,0,0,80,60,70,70,70,80,0,90,70,70,60
2574,Rebel Yell Small Batch Reserve Bourbon,Bourbon,2,45.30,10,0,30,10,10,40,50,35,10,40,0,40,0
1353,Wood's High Mountain Distillery Tenderfoot Whi...,Other Whiskey,2,45.00,40,0,60,30,20,50,50,60,0,40,40,50,0
3534,Triple Crown Blended Whiskey,Blended American Whiskey,1,40.00,31,0,40,29,0,30,40,100,0,55,0,30,10

In [91]:
np.arange(3535)

array([   0,    1,    2, ..., 3532, 3533, 3534])

In [55]:

## 신규 사용자
mm_lfm.predict(0, np.arange(3535), )

{'loss': 'warp',
 'learning_schedule': 'adagrad',
 'no_components': 40,
 'learning_rate': 0.05,
 'k': 5,
 'n': 10,
 'rho': 0.95,
 'epsilon': 1e-06,
 'max_sampled': 10,
 'item_alpha': 0.005,
 'user_alpha': 0.0005,
 'random_state': RandomState(MT19937) at 0x1D4C2E89A40}